version: '3.8'

services:
  backend:
    image: alex7rings/gradproject-backend:latest
    environment:
      - DATABASE_URL=sqlite:////app/portfolio.db
    networks:
      - app-network

  frontend:
    image: alex7rings/gradproject-frontend:latest
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
