version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/portfolio.db
    volumes:
      - ./portfolio.db:/app/portfolio.db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./:/app
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge